/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.GitHubAPI;
import java.awt.Image;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import model.User;
import utils.Link;

/**
 *
 * @author ederc
 */
public class FrmApiGitHub extends javax.swing.JFrame {

    /**
     * Creates new form FrmApiGitHub
     */
    public FrmApiGitHub() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelPrincipal = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        lblBuscaNome = new javax.swing.JLabel();
        separador = new javax.swing.JSeparator();
        txtLogin = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jPanelInfo = new javax.swing.JPanel();
        lblId = new javax.swing.JLabel();
        lblLogin = new javax.swing.JLabel();
        lblNome = new javax.swing.JLabel();
        lblGitHubUrl = new javax.swing.JLabel();
        lblCidade = new javax.swing.JLabel();
        lblDataCriacao = new javax.swing.JLabel();
        lblId1 = new javax.swing.JLabel();
        lblLogin1 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblGitHubUrl1 = new javax.swing.JLabel();
        lblCidade1 = new javax.swing.JLabel();
        lblDataCriacao1 = new javax.swing.JLabel();
        lblArmazenarLink = new javax.swing.JLabel();
        jPanelFoto = new javax.swing.JPanel();
        lblImgUrl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Buscar Usuários Github");
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/utils/img/ico.png")).getImage());
        setResizable(false);

        jPanelPrincipal.setBackground(new java.awt.Color(69, 73, 74));
        jPanelPrincipal.setToolTipText("");

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/img/logo.png"))); // NOI18N

        lblBuscaNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblBuscaNome.setForeground(new java.awt.Color(255, 255, 255));
        lblBuscaNome.setText("Digite o login GitHub para pesquisar:");

        txtLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLogin.setForeground(new java.awt.Color(0, 0, 0));

        btnPesquisa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        jPanelInfo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblId.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblId.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfo.add(lblId, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, -1, -1));

        lblLogin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLogin.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfo.add(lblLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, -1, -1));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setToolTipText("");
        jPanelInfo.add(lblNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        lblGitHubUrl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGitHubUrl.setForeground(new java.awt.Color(0, 0, 0));
        lblGitHubUrl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblGitHubUrlMouseClicked(evt);
            }
        });
        jPanelInfo.add(lblGitHubUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, -1, -1));

        lblCidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCidade.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfo.add(lblCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        lblDataCriacao.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataCriacao.setForeground(new java.awt.Color(0, 0, 0));
        jPanelInfo.add(lblDataCriacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        lblId1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblId1.setForeground(new java.awt.Color(0, 0, 0));
        lblId1.setText("Id:");
        jPanelInfo.add(lblId1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 76, -1));

        lblLogin1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblLogin1.setForeground(new java.awt.Color(0, 0, 0));
        lblLogin1.setText("Login:");
        jPanelInfo.add(lblLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 76, -1));

        lblNome1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(0, 0, 0));
        lblNome1.setText("Nome:");
        jPanelInfo.add(lblNome1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 76, -1));

        lblGitHubUrl1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblGitHubUrl1.setForeground(new java.awt.Color(0, 0, 0));
        lblGitHubUrl1.setText("GitHub:");
        jPanelInfo.add(lblGitHubUrl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 76, -1));

        lblCidade1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblCidade1.setForeground(new java.awt.Color(0, 0, 0));
        lblCidade1.setText("Cidade:");
        jPanelInfo.add(lblCidade1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 76, -1));

        lblDataCriacao1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblDataCriacao1.setForeground(new java.awt.Color(0, 0, 0));
        lblDataCriacao1.setText("Data Criação:");
        jPanelInfo.add(lblDataCriacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 120, -1));

        lblArmazenarLink.setBackground(new java.awt.Color(187, 187, 187));
        jPanelInfo.add(lblArmazenarLink, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, -1, -1));

        jPanelFoto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblImgUrl.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lblImgUrl.setForeground(new java.awt.Color(0, 0, 0));
        jPanelFoto.add(lblImgUrl, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, -1));

        javax.swing.GroupLayout jPanelPrincipalLayout = new javax.swing.GroupLayout(jPanelPrincipal);
        jPanelPrincipal.setLayout(jPanelPrincipalLayout);
        jPanelPrincipalLayout.setHorizontalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(separador, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPrincipalLayout.createSequentialGroup()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBuscaNome)
                            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                                .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnPesquisa)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                        .addComponent(logo)))
                .addContainerGap())
        );
        jPanelPrincipalLayout.setVerticalGroup(
            jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logo)
                    .addGroup(jPanelPrincipalLayout.createSequentialGroup()
                        .addComponent(lblBuscaNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLogin, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                            .addComponent(btnPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(18, 18, 18)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 315, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed

        Image img, scaled = null;
        GitHubAPI dados = new GitHubAPI();
        User user = dados.getUser(txtLogin.getText());
        
        if (user != null) {
            lblId.setText(user.getId());
            lblLogin.setText(user.getLogin());
            lblNome.setText(user.getName());
            lblGitHubUrl.setText("<html><a href=''> " + user.getHtml_url() + " </a></html>");
            lblArmazenarLink.setVisible(false);
            lblArmazenarLink.setText(user.getHtml_url());
            lblCidade.setText(user.getLocation());
            String[] data = user.getCreated_at().substring(0, 10).split("-");
            lblDataCriacao.setText(data[2] + "/" + data[1] + "/" + data[0]);
            
            try {
                URL urlImg = new URL(user.getAvatar_url());
                img = ImageIO.read(urlImg);
                scaled = img.getScaledInstance(300, 300, Image.SCALE_SMOOTH);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro ao obter imagem " + e);
            }

            lblImgUrl.setIcon(new ImageIcon(scaled));
        }

    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void lblGitHubUrlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblGitHubUrlMouseClicked
        
        Link.abrir(lblArmazenarLink.getText());
        
    }//GEN-LAST:event_lblGitHubUrlMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmApiGitHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmApiGitHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmApiGitHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmApiGitHub.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmApiGitHub().setVisible(true);
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JPanel jPanelFoto;
    private javax.swing.JPanel jPanelInfo;
    private javax.swing.JPanel jPanelPrincipal;
    private javax.swing.JLabel lblArmazenarLink;
    private javax.swing.JLabel lblBuscaNome;
    private javax.swing.JLabel lblCidade;
    private javax.swing.JLabel lblCidade1;
    private javax.swing.JLabel lblDataCriacao;
    private javax.swing.JLabel lblDataCriacao1;
    private javax.swing.JLabel lblGitHubUrl;
    private javax.swing.JLabel lblGitHubUrl1;
    private javax.swing.JLabel lblId;
    private javax.swing.JLabel lblId1;
    private javax.swing.JLabel lblImgUrl;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblLogin1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JLabel logo;
    private javax.swing.JSeparator separador;
    private javax.swing.JTextField txtLogin;
    // End of variables declaration//GEN-END:variables
}
